### ISSUE TITLE
Problem with dots in folder name

### ISSUE THREAD

**Issue by dragomano** [jdarwood007/smfmod_devtools#1]
I decided to pair this mod with Simple Mod Maker, but ran into a problem: if the folder name has a dot in it, the package will not appear in your list. For example, "mod_name_0.1".

**Comment by jdarwood007** [comment]
#3 should fix this up, I use the already existing method to check if its a valid package.  Its a bit slower because we do file stat checks, but there isn't enough mods (hopefully) to make that a noticeable impact.
