### ISSUE TITLE
Download archive as a new button

### ISSUE THREAD

**Issue by dragomano** [jdarwood007/smfmod_devtools#2]
It would be nice to have in the interface a button to download the mod directory in the form of an archive.

**Comment by jdarwood007** [comment]
Interesting idea.  Would cleanup yet another script I have around for packing up my customizations.  Would have to handle both tar.gz and zip with both exec and PharArchive..  I would want to have it handle a non standard data in the package-info.xml but this would help the tool 'build' properly

Maybe something like this:
```
	<devtools>
		<basename>{Package-Name}_{version}</basename>
		<exclude>
			<match>.git</match>
			<match>docs</match>
			<match>.*</match>
		</execlude>
	</devtools>
```
So now this would know how to format the file names and add excludes (files we don't package) into something we can use.
